---
- hosts: localhost
  become: yes
  tasks:
  - name: install nginx
    apt: name=nginx state=present update_cache=yes
   
  - name: ensure nginx started
    service: name=nginx state=stopped enabled=yes
