---
- hosts: localhost
  become: yes
  tasks:
  - name: install web components
    apt: name= {{item}} update_cache=yes state=latest
    with_items:
    - apache2
    - libapache2-mod-wsgi
    - python-pip
    - python-virtualenv
   
    
